<?php

namespace ContainerG6pseF9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCar2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.KNAnNql.App\Entity\Car' shared service.
     *
     * @return \App\Entity\Car
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.KNAnNql": it needs an instance of "App\\Entity\\Car" but this type has been excluded in "config/services.yaml".');
    }
}
