<?php

namespace ContainerZDVQM9F;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PqW8BXlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pqW8BXl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pqW8BXl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'make' => ['privates', '.errored..service_locator.pqW8BXl.App\\Entity\\Make', NULL, 'Cannot autowire service ".service_locator.pqW8BXl": it needs an instance of "App\\Entity\\Make" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'make' => 'App\\Entity\\Make',
        ]);
    }
}
