<?php

namespace ContainerZDVQM9F;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RslIKULService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RslIKUL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RslIKUL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'phone' => ['privates', '.errored..service_locator.RslIKUL.App\\Entity\\Phone', NULL, 'Cannot autowire service ".service_locator.RslIKUL": it needs an instance of "App\\Entity\\Phone" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'phone' => 'App\\Entity\\Phone',
        ]);
    }
}
