<?php

namespace ContainerZDVQM9F;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BL7V77LService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bL7V77L' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bL7V77L'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\CarController::delete' => ['privates', '.service_locator.KNAnNql', 'get_ServiceLocator_KNAnNqlService', true],
            'App\\Controller\\CarController::edit' => ['privates', '.service_locator.KNAnNql', 'get_ServiceLocator_KNAnNqlService', true],
            'App\\Controller\\CarController::index' => ['privates', '.service_locator.3LuXUDl', 'get_ServiceLocator_3LuXUDlService', true],
            'App\\Controller\\CarController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CarController::show' => ['privates', '.service_locator.2lTRklS', 'get_ServiceLocator_2lTRklSService', true],
            'App\\Controller\\MakeController::delete' => ['privates', '.service_locator.pqW8BXl', 'get_ServiceLocator_PqW8BXlService', true],
            'App\\Controller\\MakeController::edit' => ['privates', '.service_locator.pqW8BXl', 'get_ServiceLocator_PqW8BXlService', true],
            'App\\Controller\\MakeController::index' => ['privates', '.service_locator.E4_nNM8', 'get_ServiceLocator_E4NNM8Service', true],
            'App\\Controller\\MakeController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\MakeController::show' => ['privates', '.service_locator._ZSQXxZ', 'get_ServiceLocator_ZSQXxZService', true],
            'App\\Controller\\PhoneController::delete' => ['privates', '.service_locator.RslIKUL', 'get_ServiceLocator_RslIKULService', true],
            'App\\Controller\\PhoneController::edit' => ['privates', '.service_locator.RslIKUL', 'get_ServiceLocator_RslIKULService', true],
            'App\\Controller\\PhoneController::index' => ['privates', '.service_locator.9sfv9l4', 'get_ServiceLocator_9sfv9l4Service', true],
            'App\\Controller\\PhoneController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\PhoneController::show' => ['privates', '.service_locator.LU8QvKj', 'get_ServiceLocator_LU8QvKjService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.R0Sb2kd', 'get_ServiceLocator_R0Sb2kdService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.R0Sb2kd', 'get_ServiceLocator_R0Sb2kdService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\UserController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\CarController:delete' => ['privates', '.service_locator.KNAnNql', 'get_ServiceLocator_KNAnNqlService', true],
            'App\\Controller\\CarController:edit' => ['privates', '.service_locator.KNAnNql', 'get_ServiceLocator_KNAnNqlService', true],
            'App\\Controller\\CarController:index' => ['privates', '.service_locator.3LuXUDl', 'get_ServiceLocator_3LuXUDlService', true],
            'App\\Controller\\CarController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CarController:show' => ['privates', '.service_locator.2lTRklS', 'get_ServiceLocator_2lTRklSService', true],
            'App\\Controller\\MakeController:delete' => ['privates', '.service_locator.pqW8BXl', 'get_ServiceLocator_PqW8BXlService', true],
            'App\\Controller\\MakeController:edit' => ['privates', '.service_locator.pqW8BXl', 'get_ServiceLocator_PqW8BXlService', true],
            'App\\Controller\\MakeController:index' => ['privates', '.service_locator.E4_nNM8', 'get_ServiceLocator_E4NNM8Service', true],
            'App\\Controller\\MakeController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\MakeController:show' => ['privates', '.service_locator._ZSQXxZ', 'get_ServiceLocator_ZSQXxZService', true],
            'App\\Controller\\PhoneController:delete' => ['privates', '.service_locator.RslIKUL', 'get_ServiceLocator_RslIKULService', true],
            'App\\Controller\\PhoneController:edit' => ['privates', '.service_locator.RslIKUL', 'get_ServiceLocator_RslIKULService', true],
            'App\\Controller\\PhoneController:index' => ['privates', '.service_locator.9sfv9l4', 'get_ServiceLocator_9sfv9l4Service', true],
            'App\\Controller\\PhoneController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\PhoneController:show' => ['privates', '.service_locator.LU8QvKj', 'get_ServiceLocator_LU8QvKjService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.R0Sb2kd', 'get_ServiceLocator_R0Sb2kdService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.R0Sb2kd', 'get_ServiceLocator_R0Sb2kdService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\UserController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\CarController::delete' => '?',
            'App\\Controller\\CarController::edit' => '?',
            'App\\Controller\\CarController::index' => '?',
            'App\\Controller\\CarController::new' => '?',
            'App\\Controller\\CarController::show' => '?',
            'App\\Controller\\MakeController::delete' => '?',
            'App\\Controller\\MakeController::edit' => '?',
            'App\\Controller\\MakeController::index' => '?',
            'App\\Controller\\MakeController::new' => '?',
            'App\\Controller\\MakeController::show' => '?',
            'App\\Controller\\PhoneController::delete' => '?',
            'App\\Controller\\PhoneController::edit' => '?',
            'App\\Controller\\PhoneController::index' => '?',
            'App\\Controller\\PhoneController::new' => '?',
            'App\\Controller\\PhoneController::show' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::new' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CarController:delete' => '?',
            'App\\Controller\\CarController:edit' => '?',
            'App\\Controller\\CarController:index' => '?',
            'App\\Controller\\CarController:new' => '?',
            'App\\Controller\\CarController:show' => '?',
            'App\\Controller\\MakeController:delete' => '?',
            'App\\Controller\\MakeController:edit' => '?',
            'App\\Controller\\MakeController:index' => '?',
            'App\\Controller\\MakeController:new' => '?',
            'App\\Controller\\MakeController:show' => '?',
            'App\\Controller\\PhoneController:delete' => '?',
            'App\\Controller\\PhoneController:edit' => '?',
            'App\\Controller\\PhoneController:index' => '?',
            'App\\Controller\\PhoneController:new' => '?',
            'App\\Controller\\PhoneController:show' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:new' => '?',
            'App\\Controller\\UserController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
