<?php

namespace ContainerZDVQM9F;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMakeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator._ZSQXxZ.App\Entity\Make' shared service.
     *
     * @return \App\Entity\Make
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator._ZSQXxZ": it needs an instance of "App\\Entity\\Make" but this type has been excluded in "config/services.yaml".');
    }
}
