<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG6pseF9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG6pseF9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerG6pseF9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerG6pseF9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerG6pseF9\App_KernelDevDebugContainer([
    'container.build_hash' => 'G6pseF9',
    'container.build_id' => '2aff0e7f',
    'container.build_time' => 1712416233,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG6pseF9');
