<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPACqn4X\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPACqn4X/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPACqn4X.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPACqn4X\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPACqn4X\App_KernelDevDebugContainer([
    'container.build_hash' => 'PACqn4X',
    'container.build_id' => 'd3a56117',
    'container.build_time' => 1712417777,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPACqn4X');
